<?php
/**
 * ActivityModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalAccountPortal
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Account Portal API
 *
 * Bumbal Account API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BumbalAccountPortal\Model;

use \ArrayAccess;

/**
 * ActivityModel Class Doc Comment
 *
 * @category    Class
 * @package     BumbalAccountPortal
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ActivityModel implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ActivityModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'nr' => 'string',
        'assignment_nr' => 'string',
        'activity_type_id' => 'int',
        'activity_type_name' => 'string',
        'status_name' => 'string',
        'activity_tags' => 'int',
        'reference' => 'string',
        'duration' => 'int',
        'date_time_from' => '\DateTime',
        'date_time_to' => '\DateTime',
        'address' => '\BumbalAccountPortal\Model\AddressModel',
        'communication' => '\BumbalAccountPortal\Model\CommunicationModel',
        'package_lines' => '\BumbalAccountPortal\Model\PackageLineModel[]',
        'notes' => '\BumbalAccountPortal\Model\NoteModel[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'nr' => null,
        'assignment_nr' => null,
        'activity_type_id' => null,
        'activity_type_name' => null,
        'status_name' => null,
        'activity_tags' => null,
        'reference' => null,
        'duration' => null,
        'date_time_from' => 'date-time',
        'date_time_to' => 'date-time',
        'address' => null,
        'communication' => null,
        'package_lines' => null,
        'notes' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'nr' => 'nr',
        'assignment_nr' => 'assignment_nr',
        'activity_type_id' => 'activity_type_id',
        'activity_type_name' => 'activity_type_name',
        'status_name' => 'status_name',
        'activity_tags' => 'activity_tags',
        'reference' => 'reference',
        'duration' => 'duration',
        'date_time_from' => 'date_time_from',
        'date_time_to' => 'date_time_to',
        'address' => 'address',
        'communication' => 'communication',
        'package_lines' => 'package_lines',
        'notes' => 'notes'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'nr' => 'setNr',
        'assignment_nr' => 'setAssignmentNr',
        'activity_type_id' => 'setActivityTypeId',
        'activity_type_name' => 'setActivityTypeName',
        'status_name' => 'setStatusName',
        'activity_tags' => 'setActivityTags',
        'reference' => 'setReference',
        'duration' => 'setDuration',
        'date_time_from' => 'setDateTimeFrom',
        'date_time_to' => 'setDateTimeTo',
        'address' => 'setAddress',
        'communication' => 'setCommunication',
        'package_lines' => 'setPackageLines',
        'notes' => 'setNotes'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'nr' => 'getNr',
        'assignment_nr' => 'getAssignmentNr',
        'activity_type_id' => 'getActivityTypeId',
        'activity_type_name' => 'getActivityTypeName',
        'status_name' => 'getStatusName',
        'activity_tags' => 'getActivityTags',
        'reference' => 'getReference',
        'duration' => 'getDuration',
        'date_time_from' => 'getDateTimeFrom',
        'date_time_to' => 'getDateTimeTo',
        'address' => 'getAddress',
        'communication' => 'getCommunication',
        'package_lines' => 'getPackageLines',
        'notes' => 'getNotes'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['nr'] = isset($data['nr']) ? $data['nr'] : null;
        $this->container['assignment_nr'] = isset($data['assignment_nr']) ? $data['assignment_nr'] : null;
        $this->container['activity_type_id'] = isset($data['activity_type_id']) ? $data['activity_type_id'] : null;
        $this->container['activity_type_name'] = isset($data['activity_type_name']) ? $data['activity_type_name'] : null;
        $this->container['status_name'] = isset($data['status_name']) ? $data['status_name'] : null;
        $this->container['activity_tags'] = isset($data['activity_tags']) ? $data['activity_tags'] : null;
        $this->container['reference'] = isset($data['reference']) ? $data['reference'] : null;
        $this->container['duration'] = isset($data['duration']) ? $data['duration'] : null;
        $this->container['date_time_from'] = isset($data['date_time_from']) ? $data['date_time_from'] : null;
        $this->container['date_time_to'] = isset($data['date_time_to']) ? $data['date_time_to'] : null;
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
        $this->container['communication'] = isset($data['communication']) ? $data['communication'] : null;
        $this->container['package_lines'] = isset($data['package_lines']) ? $data['package_lines'] : null;
        $this->container['notes'] = isset($data['notes']) ? $data['notes'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id ID of this Activity
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets nr
     * @return string
     */
    public function getNr()
    {
        return $this->container['nr'];
    }

    /**
     * Sets nr
     * @param string $nr Number of this Activity
     * @return $this
     */
    public function setNr($nr)
    {
        $this->container['nr'] = $nr;

        return $this;
    }

    /**
     * Gets assignment_nr
     * @return string
     */
    public function getAssignmentNr()
    {
        return $this->container['assignment_nr'];
    }

    /**
     * Sets assignment_nr
     * @param string $assignment_nr Assignment Number
     * @return $this
     */
    public function setAssignmentNr($assignment_nr)
    {
        $this->container['assignment_nr'] = $assignment_nr;

        return $this;
    }

    /**
     * Gets activity_type_id
     * @return int
     */
    public function getActivityTypeId()
    {
        return $this->container['activity_type_id'];
    }

    /**
     * Sets activity_type_id
     * @param int $activity_type_id Type ID of this Activity
     * @return $this
     */
    public function setActivityTypeId($activity_type_id)
    {
        $this->container['activity_type_id'] = $activity_type_id;

        return $this;
    }

    /**
     * Gets activity_type_name
     * @return string
     */
    public function getActivityTypeName()
    {
        return $this->container['activity_type_name'];
    }

    /**
     * Sets activity_type_name
     * @param string $activity_type_name Type of this Activity
     * @return $this
     */
    public function setActivityTypeName($activity_type_name)
    {
        $this->container['activity_type_name'] = $activity_type_name;

        return $this;
    }

    /**
     * Gets status_name
     * @return string
     */
    public function getStatusName()
    {
        return $this->container['status_name'];
    }

    /**
     * Sets status_name
     * @param string $status_name Status of this Activity
     * @return $this
     */
    public function setStatusName($status_name)
    {
        $this->container['status_name'] = $status_name;

        return $this;
    }

    /**
     * Gets activity_tags
     * @return int
     */
    public function getActivityTags()
    {
        return $this->container['activity_tags'];
    }

    /**
     * Sets activity_tags
     * @param int $activity_tags Single Tag to attach to Activity
     * @return $this
     */
    public function setActivityTags($activity_tags)
    {
        $this->container['activity_tags'] = $activity_tags;

        return $this;
    }

    /**
     * Gets reference
     * @return string
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     * @param string $reference Reference number
     * @return $this
     */
    public function setReference($reference)
    {
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets duration
     * @return int
     */
    public function getDuration()
    {
        return $this->container['duration'];
    }

    /**
     * Sets duration
     * @param int $duration Max duration of the activity in minutes
     * @return $this
     */
    public function setDuration($duration)
    {
        $this->container['duration'] = $duration;

        return $this;
    }

    /**
     * Gets date_time_from
     * @return \DateTime
     */
    public function getDateTimeFrom()
    {
        return $this->container['date_time_from'];
    }

    /**
     * Sets date_time_from
     * @param \DateTime $date_time_from Planned start time of this activity
     * @return $this
     */
    public function setDateTimeFrom($date_time_from)
    {
        $this->container['date_time_from'] = $date_time_from;

        return $this;
    }

    /**
     * Gets date_time_to
     * @return \DateTime
     */
    public function getDateTimeTo()
    {
        return $this->container['date_time_to'];
    }

    /**
     * Sets date_time_to
     * @param \DateTime $date_time_to Planned stop time of this activity
     * @return $this
     */
    public function setDateTimeTo($date_time_to)
    {
        $this->container['date_time_to'] = $date_time_to;

        return $this;
    }

    /**
     * Gets address
     * @return \BumbalAccountPortal\Model\AddressModel
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     * @param \BumbalAccountPortal\Model\AddressModel $address
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets communication
     * @return \BumbalAccountPortal\Model\CommunicationModel
     */
    public function getCommunication()
    {
        return $this->container['communication'];
    }

    /**
     * Sets communication
     * @param \BumbalAccountPortal\Model\CommunicationModel $communication
     * @return $this
     */
    public function setCommunication($communication)
    {
        $this->container['communication'] = $communication;

        return $this;
    }

    /**
     * Gets package_lines
     * @return \BumbalAccountPortal\Model\PackageLineModel[]
     */
    public function getPackageLines()
    {
        return $this->container['package_lines'];
    }

    /**
     * Sets package_lines
     * @param \BumbalAccountPortal\Model\PackageLineModel[] $package_lines
     * @return $this
     */
    public function setPackageLines($package_lines)
    {
        $this->container['package_lines'] = $package_lines;

        return $this;
    }

    /**
     * Gets notes
     * @return \BumbalAccountPortal\Model\NoteModel[]
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     * @param \BumbalAccountPortal\Model\NoteModel[] $notes
     * @return $this
     */
    public function setNotes($notes)
    {
        $this->container['notes'] = $notes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\BumbalAccountPortal\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\BumbalAccountPortal\ObjectSerializer::sanitizeForSerialization($this));
    }
}


