<?php
/**
 * CommunicationModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalAccountPortal
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Account Portal API
 *
 * Bumbal Account API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalAccountPortal;

/**
 * CommunicationModelTest Class Doc Comment
 *
 * @category    Class */
// * @description CommunicationModel
/**
 * @package     BumbalAccountPortal
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CommunicationModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CommunicationModel"
     */
    public function testCommunicationModel()
    {
    }

    /**
     * Test attribute "saywhen"
     */
    public function testPropertySaywhen()
    {
    }

    /**
     * Test attribute "bumbal"
     */
    public function testPropertyBumbal()
    {
    }

    /**
     * Test attribute "send_invite"
     */
    public function testPropertySendInvite()
    {
    }

    /**
     * Test attribute "send_eta"
     */
    public function testPropertySendEta()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "phone_nr"
     */
    public function testPropertyPhoneNr()
    {
    }
}
