<?php
/**
 * ActivityApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalAccountPortal
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Account Portal API
 *
 * Bumbal Account API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalAccountPortal;

use \BumbalAccountPortal\Configuration;
use \BumbalAccountPortal\ApiClient;
use \BumbalAccountPortal\ApiException;
use \BumbalAccountPortal\ObjectSerializer;

/**
 * ActivityApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalAccountPortal
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ActivityApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteActivity
     *
     * Delete an activity.
     *
     */
    public function testDeleteActivity()
    {
    }

    /**
     * Test case for retrieveActivity
     *
     * Find activity by ID.
     *
     */
    public function testRetrieveActivity()
    {
    }

    /**
     * Test case for setActivity
     *
     * Set an activity.
     *
     */
    public function testSetActivity()
    {
    }
}
